### ISSUE TITLE
Error on running it.

### ISSUE THREAD

**Issue by vhbsouza** [ids1024/wikicurses#2]
I'm trying to run wikicurses and is showing this Python error output.

``` zsh
  File "/usr/local/bin/wikicurses", line 33
    print(*sugestions, sep='\n')
          ^
SyntaxError: invalid syntax

```

Can someone help me?

**Comment by lahwaacz** [comment]
That is a valid Python 3 syntax, but you are most likely running it in Python 2.

**Comment by ids1024** [comment]
Yes, wikicurses is python 3 only. What version of python are you using?
